[theme]
primaryColor = "#003B6F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#2C3E50"
font = "sans serif"

[server]
maxUploadSize = 20
enableXsrfProtection = true

[browser]
gatherUsageStats = false
